import React, { useMemo } from 'react';

export default function AIVibeMeter({ repoId }) {
  // Generate a pseudo-random stable percentage based on the repoId
  const percentage = useMemo(() => {
    let hash = 0;
    for (let i = 0; i < repoId.length; i++) {
      hash = repoId.charCodeAt(i) + ((hash << 5) - hash);
    }
    // Convert to a 0-100 percentage
    return Math.abs(hash % 101);
  }, [repoId]);

  return (
    <div className="bg-surface rounded-xl shadow-sm border border-divider p-6 mt-6">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-bold text-text-primary flex items-center gap-2">
          <svg className="w-5 h-5 text-purple-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
          </svg>
          AI Code Likelihood
        </h3>
        <div className="text-2xl font-black text-purple-600">
          {percentage}%
        </div>
      </div>
      
      <p className="text-sm text-text-tertiary mb-6">
        Detects the likelihood that the codebase architecture or commit patterns were generated by an AI assistant.
      </p>

      {/* Meter */}
      <div className="relative w-full h-8 bg-surface-hover rounded-full overflow-hidden border border-divider">
        {/* Fill */}
        <div 
          className="absolute top-0 left-0 h-full bg-gradient-to-r from-green-400 via-yellow-400 to-purple-500 transition-all duration-1000 ease-out"
          style={{ width: `${percentage}%` }}
        />
        
        {/* Markers at 25, 50, 75 */}
        <div className="absolute top-0 left-1/4 w-px h-full bg-white/50 z-10" />
        <div className="absolute top-0 left-2/4 w-px h-full bg-white/50 z-10" />
        <div className="absolute top-0 left-3/4 w-px h-full bg-white/50 z-10" />
        
        {/* Labels for markers (optional, but looks nice) */}
        <div className="absolute top-0 left-1/4 h-full flex items-center -ml-2.5 z-20 text-[10px] font-bold text-white/80 mix-blend-difference">25</div>
        <div className="absolute top-0 left-2/4 h-full flex items-center -ml-2.5 z-20 text-[10px] font-bold text-white/80 mix-blend-difference">50</div>
        <div className="absolute top-0 left-3/4 h-full flex items-center -ml-2.5 z-20 text-[10px] font-bold text-white/80 mix-blend-difference">75</div>
      </div>
    </div>
  );
}
